version: 2.1
jobs:
  build:
    docker:
      - image: worldturtlemedia/flutter_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Flutter doctor
          command: flutter doctor -v
      - run:
          name: Get packages for the Flutter project
          command: flutter pub get
      - run:
          name: Analyze the project’s Dart code
          command: flutter analyze
      - run:
          name: Ensure the Dart code is formatted correctly
          command: flutter format --set-exit-if-changed --dry-run .
      - run:
          name: Run Flutter unit tests
          command: flutter test
      - run:
          name: Publish package
          command: npm run semantic-release
