version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor -v
      - run:
          name: Get packages for the Flutter project
          command: flutter pub get
      - run:
          name: Analyze the project’s Dart code
          command: flutter analyze
      - run:
          name: Ensure the Dart code is formatted correctly
          command: flutter format --set-exit-if-changed --dry-run .
      - run:
          name: Run Flutter unit tests
          command: flutter test

